/**
 * Справочники приложения: блюда, упражнения, привычки и статьи.
 * Данные используются только локально, без отправки на сервер.
 */
window.APP_DATA = {
  allergens: [
    { id: "milk", label: "Молоко и молочные продукты" },
    { id: "egg", label: "Яйца" },
    { id: "gluten", label: "Глютен (пшеница, рожь, ячмень)" },
    { id: "nuts", label: "Орехи" },
    { id: "peanut", label: "Арахис" },
    { id: "fish", label: "Рыба" },
    { id: "soy", label: "Соя" },
    { id: "sesame", label: "Кунжут" }
  ],

  shoppingCategories: {
    vegetables: "Овощи и зелень",
    fruits: "Фрукты и ягоды",
    protein: "Белковые продукты",
    grains: "Крупы, хлеб и гарниры",
    dairy: "Молочные продукты",
    fats: "Масла, орехи и семена",
    other: "Другое"
  },

  habits: [
    { id: "walk", title: "Короткая прогулка", hint: "10–20 минут в комфортном темпе." },
    { id: "sit-break", title: "Перерыв от сидения", hint: "Каждые 45–60 минут встаньте и разомнитесь." },
    { id: "regular-meals", title: "Регулярное питание", hint: "Приёмы пищи без длительных голодных окон, если врач не рекомендовал иное." },
    { id: "sleep", title: "Достаточный сон", hint: "Ориентир — стабильный режим, а не «норма для всех»." },
    { id: "shopping-plan", title: "Планирование покупок", hint: "Список снижает импульсивные покупки и упрощает готовку." },
    { id: "plants", title: "Овощи или фрукты", hint: "Добавьте порцию овощей или фруктов хотя бы в один приём пищи." },
    { id: "protein", title: "Источник белка", hint: "В основных приёмах пищи — яйца, бобовые, рыба, птица, тофу или кисломолочные продукты." },
    { id: "hunger", title: "Голод и насыщение", hint: "Перед едой коротко отметьте: физический голод или привычка/эмоции." },
    { id: "stress", title: "Управление стрессом", hint: "5–10 минут дыхания, прогулки или спокойного занятия без экрана." },
    { id: "prep", title: "Подготовка еды заранее", hint: "Даже одно блюдо, приготовленное заранее, упрощает день." }
  ],

  recipes: [
    { id: "oat-berries", name: "Овсянка с ягодами", meal: "breakfast", kcal: 390, protein: 14, fat: 11, carbs: 58, portion: "1 тарелка, около 350 г", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["gluten", "milk"], ingredients: [{ name: "Овсяные хлопья", amount: "60 г", category: "grains" }, { name: "Молоко 2,5%", amount: "200 мл", category: "dairy" }, { name: "Ягоды", amount: "80 г", category: "fruits" }, { name: "Семена льна", amount: "1 ч. л.", category: "fats" }], method: "Залейте хлопья молоком, прогрейте 5–7 минут, добавьте ягоды и семена.", swaps: ["Творог с фруктами", "Греческий йогурт с овсянкой", "Овсянка на растительном молоке"] },
    { id: "yogurt-granola", name: "Йогурт с гранолой и яблоком", meal: "breakfast", kcal: 370, protein: 18, fat: 10, carbs: 48, portion: "чашка 300 г", vegetarian: true, vegan: false, budget: "medium", cook: "quick", allergens: ["milk", "gluten", "nuts"], ingredients: [{ name: "Натуральный йогурт", amount: "250 г", category: "dairy" }, { name: "Гранола без излишнего сахара", amount: "30 г", category: "grains" }, { name: "Яблоко", amount: "1 шт.", category: "fruits" }], method: "Сложите йогурт, гранолу и нарезанное яблоко.", swaps: ["Творожная миска", "Кефир с мюсли", "Овсянка с ягодами"] },
    { id: "veg-omelet", name: "Омлет с овощами и тостом", meal: "breakfast", kcal: 410, protein: 24, fat: 22, carbs: 28, portion: "2 яйца и 1 тост", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["egg", "gluten"], ingredients: [{ name: "Яйца", amount: "2 шт.", category: "protein" }, { name: "Помидор и шпинат", amount: "120 г", category: "vegetables" }, { name: "Цельнозерновой хлеб", amount: "1 ломтик", category: "grains" }, { name: "Растительное масло", amount: "1 ч. л.", category: "fats" }], method: "Обжарьте овощи, залейте яйцами, подайте с тостом.", swaps: ["Яйца всмятку с овощами", "Творог с овощным салатом", "Тофу-скрэмбл"] },
    { id: "cottage-bowl", name: "Творожная миска с грушей", meal: "breakfast", kcal: 360, protein: 28, fat: 8, carbs: 40, portion: "тарелка 280 г", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["milk"], ingredients: [{ name: "Творог 5%", amount: "180 г", category: "dairy" }, { name: "Груша", amount: "1 шт.", category: "fruits" }, { name: "Корица", amount: "по вкусу", category: "other" }], method: "Смешайте творог с нарезанной грушей и корицей.", swaps: ["Йогурт с ягодами", "Овсянка с молоком", "Кефир с бананом"] },
    { id: "oat-pancakes", name: "Овсяные оладьи с ягодами", meal: "breakfast", kcal: 420, protein: 16, fat: 12, carbs: 60, portion: "3 небольших оладья", vegetarian: true, vegan: false, budget: "low", cook: "medium", allergens: ["gluten", "egg", "milk"], ingredients: [{ name: "Овсяные хлопья", amount: "70 г", category: "grains" }, { name: "Яйцо", amount: "1 шт.", category: "protein" }, { name: "Кефир", amount: "80 мл", category: "dairy" }, { name: "Ягоды", amount: "60 г", category: "fruits" }], method: "Измельчите хлопья, смешайте с яйцом и кефиром, жарьте на антипригарной сковороде.", swaps: ["Овсянка с ягодами", "Творожная запеканка", "Тост с яйцом"] },
    { id: "tofu-scramble", name: "Тофу-скрэмбл с овощами", meal: "breakfast", kcal: 380, protein: 22, fat: 18, carbs: 28, portion: "тарелка 320 г", vegetarian: true, vegan: true, budget: "medium", cook: "quick", allergens: ["soy", "gluten"], ingredients: [{ name: "Тофу", amount: "150 г", category: "protein" }, { name: "Перец и кабачок", amount: "150 г", category: "vegetables" }, { name: "Куркума", amount: "щепотка", category: "other" }, { name: "Цельнозерновой хлеб", amount: "1 ломтик", category: "grains" }], method: "Разомните тофу, обжарьте с овощами 6–8 минут, подайте с хлебом.", swaps: ["Нут с овощами", "Овсянка на растительном молоке", "Хумус с овощами"] },
    { id: "overnight-oats", name: "Ночная овсянка на растительном молоке", meal: "breakfast", kcal: 400, protein: 12, fat: 13, carbs: 58, portion: "банка 350 г", vegetarian: true, vegan: true, budget: "low", cook: "quick", allergens: ["gluten"], ingredients: [{ name: "Овсяные хлопья", amount: "60 г", category: "grains" }, { name: "Растительное молоко", amount: "200 мл", category: "other" }, { name: "Банан", amount: "1 шт.", category: "fruits" }, { name: "Семена чиа", amount: "1 ч. л.", category: "fats" }], method: "Смешайте вечером, уберите в холодильник, утром добавьте банан.", swaps: ["Тофу-скрэмбл", "Каша из гречки с фруктами", "Тост с арахисовой пастой"] },

    { id: "chicken-buckwheat", name: "Курица с гречкой и салатом", meal: "lunch", kcal: 520, protein: 38, fat: 14, carbs: 54, portion: "тарелка 450 г", vegetarian: false, vegan: false, budget: "low", cook: "medium", allergens: [], ingredients: [{ name: "Куриное филе", amount: "140 г", category: "protein" }, { name: "Гречка", amount: "60 г сухого", category: "grains" }, { name: "Огурец и зелень", amount: "150 г", category: "vegetables" }, { name: "Растительное масло", amount: "1 ч. л.", category: "fats" }], method: "Запеките или потушите филе, отварите гречку, соберите с салатом.", swaps: ["Индейка с рисом", "Рыба с картофелем", "Чечевичный суп"] },
    { id: "turkey-salad", name: "Салат с индейкой и крупой", meal: "lunch", kcal: 480, protein: 36, fat: 16, carbs: 42, portion: "большая миска", vegetarian: false, vegan: false, budget: "medium", cook: "medium", allergens: [], ingredients: [{ name: "Индейка", amount: "130 г", category: "protein" }, { name: "Бурый рис", amount: "50 г сухого", category: "grains" }, { name: "Смесь салата", amount: "120 г", category: "vegetables" }, { name: "Оливковое масло", amount: "1 ч. л.", category: "fats" }], method: "Смешайте готовую индейку, рис и овощи, заправьте маслом.", swaps: ["Курица с гречкой", "Нутовый боул", "Рыбный салат"] },
    { id: "lentil-soup", name: "Чечевичный суп с хлебом", meal: "lunch", kcal: 450, protein: 24, fat: 10, carbs: 64, portion: "тарелка 400 г и 1 ломтик хлеба", vegetarian: true, vegan: true, budget: "low", cook: "medium", allergens: ["gluten"], ingredients: [{ name: "Красная чечевица", amount: "70 г", category: "protein" }, { name: "Морковь и лук", amount: "150 г", category: "vegetables" }, { name: "Томатная паста", amount: "1 ст. л.", category: "other" }, { name: "Цельнозерновой хлеб", amount: "1 ломтик", category: "grains" }], method: "Тушите овощи, добавьте чечевицу и воду, варите 20 минут.", swaps: ["Нутовый боул", "Овощное рагу с фасолью", "Гречка с тофу"] },
    { id: "fish-potato", name: "Запечённая рыба с картофелем", meal: "lunch", kcal: 510, protein: 34, fat: 16, carbs: 50, portion: "тарелка 420 г", vegetarian: false, vegan: false, budget: "medium", cook: "medium", allergens: ["fish"], ingredients: [{ name: "Белая рыба", amount: "150 г", category: "protein" }, { name: "Картофель", amount: "200 г", category: "grains" }, { name: "Брокколи", amount: "150 г", category: "vegetables" }, { name: "Лимон", amount: "долька", category: "fruits" }], method: "Запеките рыбу и картофель 20–25 минут, брокколи отварите или приготовьте на пару.", swaps: ["Курица с гречкой", "Индейка с салатом", "Тофу с рисом"] },
    { id: "chickpea-bowl", name: "Боул с нутом и овощами", meal: "lunch", kcal: 500, protein: 20, fat: 16, carbs: 68, portion: "миска 450 г", vegetarian: true, vegan: true, budget: "low", cook: "medium", allergens: ["sesame"], ingredients: [{ name: "Нут варёный", amount: "180 г", category: "protein" }, { name: "Киноа или рис", amount: "50 г сухого", category: "grains" }, { name: "Огурцы, морковь, зелень", amount: "180 г", category: "vegetables" }, { name: "Тахини или масло", amount: "1 ч. л.", category: "fats" }], method: "Соберите крупу, нут и свежие овощи, заправьте.", swaps: ["Чечевичный суп", "Тофу с овощами", "Фасолевое рагу"] },
    { id: "beef-stew", name: "Тушёная говядина с овощами", meal: "lunch", kcal: 540, protein: 36, fat: 20, carbs: 44, portion: "тарелка 430 г", vegetarian: false, vegan: false, budget: "medium", cook: "medium", allergens: [], ingredients: [{ name: "Говядина", amount: "130 г", category: "protein" }, { name: "Морковь и перец", amount: "180 г", category: "vegetables" }, { name: "Гречка или рис", amount: "50 г сухого", category: "grains" }], method: "Тушите мясо с овощами до мягкости, подайте с крупой.", swaps: ["Курица с гречкой", "Индейка с рисом", "Чечевица с овощами"] },
    { id: "pasta-turkey", name: "Цельнозерновая паста с индейкой", meal: "lunch", kcal: 530, protein: 34, fat: 14, carbs: 64, portion: "тарелка 400 г", vegetarian: false, vegan: false, budget: "medium", cook: "quick", allergens: ["gluten"], ingredients: [{ name: "Цельнозерновая паста", amount: "70 г сухого", category: "grains" }, { name: "Фарш индейки", amount: "120 г", category: "protein" }, { name: "Томаты и кабачок", amount: "180 г", category: "vegetables" }], method: "Обжарьте фарш с овощами, смешайте с пастой.", swaps: ["Паста с нутом", "Курица с гречкой", "Рыба с картофелем"] },

    { id: "baked-fish-quinoa", name: "Рыба с киноа и зелёным салатом", meal: "dinner", kcal: 470, protein: 36, fat: 14, carbs: 42, portion: "тарелка 400 г", vegetarian: false, vegan: false, budget: "medium", cook: "medium", allergens: ["fish"], ingredients: [{ name: "Рыба", amount: "150 г", category: "protein" }, { name: "Киноа", amount: "50 г сухого", category: "grains" }, { name: "Салатные листья", amount: "100 г", category: "vegetables" }], method: "Запеките рыбу, отварите киноа, добавьте салат.", swaps: ["Куриное рагу", "Тофу с рисом", "Индейка с кабачками"] },
    { id: "chicken-stew", name: "Куриное рагу с кабачком", meal: "dinner", kcal: 460, protein: 38, fat: 12, carbs: 38, portion: "тарелка 420 г", vegetarian: false, vegan: false, budget: "low", cook: "medium", allergens: [], ingredients: [{ name: "Курица", amount: "150 г", category: "protein" }, { name: "Кабачок и морковь", amount: "220 г", category: "vegetables" }, { name: "Рис", amount: "40 г сухого", category: "grains" }], method: "Тушите курицу с овощами, подайте с небольшой порцией риса.", swaps: ["Рыба с киноа", "Индейка с овощами", "Фасоль с овощами"] },
    { id: "tofu-rice", name: "Тофу с овощами и рисом", meal: "dinner", kcal: 450, protein: 22, fat: 16, carbs: 54, portion: "тарелка 420 г", vegetarian: true, vegan: true, budget: "medium", cook: "quick", allergens: ["soy"], ingredients: [{ name: "Тофу", amount: "160 г", category: "protein" }, { name: "Смесь овощей", amount: "200 г", category: "vegetables" }, { name: "Бурый рис", amount: "50 г сухого", category: "grains" }], method: "Обжарьте тофу и овощи, подайте с рисом.", swaps: ["Нут с овощами", "Чечевичное рагу", "Овощи с фасолью"] },
    { id: "turkey-zucchini", name: "Тефтели из индейки с кабачками", meal: "dinner", kcal: 440, protein: 34, fat: 14, carbs: 36, portion: "тарелка 400 г", vegetarian: false, vegan: false, budget: "medium", cook: "medium", allergens: ["egg", "gluten"], ingredients: [{ name: "Фарш индейки", amount: "140 г", category: "protein" }, { name: "Кабачок", amount: "200 г", category: "vegetables" }, { name: "Овсяные хлопья", amount: "20 г", category: "grains" }], method: "Сформуйте тефтели с хлопьями, запеките, подайте с тушёным кабачком.", swaps: ["Куриное рагу", "Рыба с салатом", "Творог с овощами"] },
    { id: "bean-stew", name: "Рагу из фасоли и баклажана", meal: "dinner", kcal: 430, protein: 18, fat: 12, carbs: 58, portion: "тарелка 420 г", vegetarian: true, vegan: true, budget: "low", cook: "medium", allergens: [], ingredients: [{ name: "Фасоль варёная", amount: "180 г", category: "protein" }, { name: "Баклажан и томат", amount: "250 г", category: "vegetables" }, { name: "Оливковое масло", amount: "1 ч. л.", category: "fats" }], method: "Тушите овощи с фасолью 15–20 минут.", swaps: ["Тофу с рисом", "Чечевичный суп", "Нутовый боул"] },
    { id: "cottage-salad", name: "Творог с овощным салатом", meal: "dinner", kcal: 390, protein: 30, fat: 12, carbs: 28, portion: "тарелка 350 г", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["milk"], ingredients: [{ name: "Творог 5%", amount: "180 г", category: "dairy" }, { name: "Помидор, огурец, зелень", amount: "200 г", category: "vegetables" }, { name: "Растительное масло", amount: "1 ч. л.", category: "fats" }], method: "Соберите салат и подайте с творогом.", swaps: ["Йогурт с овощами", "Омлет с салатом", "Тофу с овощами"] },
    { id: "salmon-broccoli", name: "Лосось с брокколи", meal: "dinner", kcal: 500, protein: 34, fat: 26, carbs: 22, portion: "тарелка 380 г", vegetarian: false, vegan: false, budget: "comfortable", cook: "medium", allergens: ["fish"], ingredients: [{ name: "Лосось", amount: "140 г", category: "protein" }, { name: "Брокколи", amount: "180 г", category: "vegetables" }, { name: "Картофель", amount: "120 г", category: "grains" }], method: "Запеките лосось и картофель, брокколи приготовьте на пару.", swaps: ["Белая рыба с картофелем", "Курица с овощами", "Тофу с овощами"] },

    { id: "apple-yogurt", name: "Яблоко и йогурт", meal: "snack", kcal: 180, protein: 10, fat: 3, carbs: 28, portion: "1 яблоко и 150 г йогурта", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["milk"], ingredients: [{ name: "Яблоко", amount: "1 шт.", category: "fruits" }, { name: "Натуральный йогурт", amount: "150 г", category: "dairy" }], method: "Нарежьте яблоко и подайте с йогуртом.", swaps: ["Кефир с ягодами", "Груша с творогом", "Морковь с хумусом"] },
    { id: "hummus-carrots", name: "Хумус с морковью", meal: "snack", kcal: 200, protein: 7, fat: 10, carbs: 22, portion: "70 г хумуса и овощи", vegetarian: true, vegan: true, budget: "low", cook: "quick", allergens: ["sesame"], ingredients: [{ name: "Хумус", amount: "70 г", category: "protein" }, { name: "Морковь", amount: "120 г", category: "vegetables" }], method: "Нарежьте морковь брусочками и подайте с хумусом.", swaps: ["Яблоко с арахисовой пастой", "Тофу с огурцом", "Фрукты и семена"] },
    { id: "nuts-fruit", name: "Фрукт и небольшая горсть орехов", meal: "snack", kcal: 210, protein: 5, fat: 12, carbs: 22, portion: "1 фрукт и 15 г орехов", vegetarian: true, vegan: true, budget: "medium", cook: "quick", allergens: ["nuts"], ingredients: [{ name: "Груша или яблоко", amount: "1 шт.", category: "fruits" }, { name: "Грецкие орехи", amount: "15 г", category: "fats" }], method: "Соедините фрукт и орехи как перекус.", swaps: ["Хумус с овощами", "Банан с семенами", "Йогурт с ягодами"] },
    { id: "kefir-berries", name: "Кефир с ягодами", meal: "snack", kcal: 160, protein: 9, fat: 4, carbs: 20, portion: "стакан 250 мл", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["milk"], ingredients: [{ name: "Кефир", amount: "250 мл", category: "dairy" }, { name: "Ягоды", amount: "70 г", category: "fruits" }], method: "Смешайте кефир с ягодами.", swaps: ["Йогурт с яблоком", "Творог с грушей", "Растительный йогурт с фруктами"] },
    { id: "rice-cakes-cottage", name: "Хлебцы с творогом", meal: "snack", kcal: 190, protein: 14, fat: 4, carbs: 24, portion: "2 хлебца", vegetarian: true, vegan: false, budget: "low", cook: "quick", allergens: ["milk", "gluten"], ingredients: [{ name: "Рисовые или зерновые хлебцы", amount: "2 шт.", category: "grains" }, { name: "Творог", amount: "80 г", category: "dairy" }, { name: "Огурец", amount: "50 г", category: "vegetables" }], method: "Намажьте хлебцы творогом, добавьте огурец.", swaps: ["Тост с хумусом", "Йогурт с фруктом", "Овощи с творожным соусом"] },
    { id: "banana-pb", name: "Банан с арахисовой пастой", meal: "snack", kcal: 230, protein: 6, fat: 10, carbs: 30, portion: "1 банан и 1 ч. л. пасты", vegetarian: true, vegan: true, budget: "low", cook: "quick", allergens: ["peanut"], ingredients: [{ name: "Банан", amount: "1 шт.", category: "fruits" }, { name: "Арахисовая паста без сахара", amount: "1 ч. л.", category: "fats" }], method: "Намажьте пасту на кусочки банана.", swaps: ["Яблоко с орехами", "Хумус с морковью", "Овсяные шарики"] }
  ],

  exercises: {
    warmup: [
      { id: "march", name: "Ходьба на месте", time: "2 мин", easier: "Медленная ходьба с опорой на спинку стула", avoid: [] },
      { id: "shoulder-rolls", name: "Круги плечами", time: "30 сек", easier: "Малая амплитуда", avoid: [] },
      { id: "hip-circles", name: "Мягкие круги тазом", time: "30 сек", easier: "Покачивания тазом стоя у опоры", avoid: ["hips"] },
      { id: "cat-cow", name: "Поза кошки — коровы у стула или на полу", time: "1 мин", easier: "Наклоны корпуса сидя", avoid: [] }
    ],
    cooldown: [
      { id: "walk-slow", name: "Медленная ходьба", time: "2 мин", easier: "Сидеть и спокойно дышать", avoid: [] },
      { id: "hamstring", name: "Растяжка задней поверхности бедра", time: "30 сек на сторону", easier: "Сгибание ноги сидя без наклона", avoid: ["back"] },
      { id: "chest-open", name: "Раскрытие груди у стены", time: "30 сек", easier: "Руки на поясе, мягкое сведение лопаток", avoid: [] },
      { id: "breath", name: "Дыхание 4–6", time: "1 мин", easier: "Свободное спокойное дыхание", avoid: [] }
    ],
    homeNone: [
      { id: "sit-stand", name: "Вставания со стула", sets: "2–3", reps: "8–12", rest: "45–60 сек", rpe: "5–6", easier: "Используйте подлокотники и меньшую амплитуду", avoid: ["knees", "hips"] },
      { id: "wall-push", name: "Отжимания от стены", sets: "2–3", reps: "8–12", rest: "45 сек", rpe: "4–6", easier: "Отойдите ближе к стене", avoid: [] },
      { id: "glute-bridge", name: "Ягодичный мост", sets: "2–3", reps: "8–12", rest: "45 сек", rpe: "5–6", easier: "Меньшая амплитуда или мост с опорой спины на диван", avoid: ["back"] },
      { id: "bird-dog", name: "Диагональ рука-нога с опорой", sets: "2", reps: "6–8 на сторону", rest: "45 сек", rpe: "4–5", easier: "Только руки или только ноги", avoid: ["back"] },
      { id: "standing-row", name: "Тяга эластичным полотенцем", sets: "2–3", reps: "10–12", rest: "45 сек", rpe: "4–5", easier: "Меньше натяжение", avoid: [] }
    ],
    homeBands: [
      { id: "band-squat", name: "Приседание с резинкой до комфортной глубины", sets: "2–3", reps: "8–12", rest: "60 сек", rpe: "5–7", easier: "Вставания со стула с резинкой", avoid: ["knees", "hips"] },
      { id: "band-row", name: "Тяга резинки к поясу", sets: "2–3", reps: "10–12", rest: "45 сек", rpe: "5–6", easier: "Слабее натяжение", avoid: [] },
      { id: "band-press", name: "Жим резинки вперёд", sets: "2–3", reps: "8–12", rest: "45 сек", rpe: "5–6", easier: "Меньшая амплитуда", avoid: [] },
      { id: "band-walk", name: "Боковые шаги с резинкой", sets: "2", reps: "8 шагов", rest: "45 сек", rpe: "5–6", easier: "Шаги без резинки", avoid: ["hips", "knees"] },
      { id: "band-deadlift", name: "Наклон с резинкой (румынская тяга)", sets: "2–3", reps: "8–10", rest: "60 сек", rpe: "5–6", easier: "Очень маленький наклон", avoid: ["back"] }
    ],
    homeDumbbells: [
      { id: "goblet", name: "Приседание с гантелью у груди", sets: "2–3", reps: "8–12", rest: "60 сек", rpe: "6–7", easier: "Без веса, до стула", avoid: ["knees", "hips"] },
      { id: "db-row", name: "Тяга гантели в наклоне с опорой", sets: "2–3", reps: "8–12", rest: "45 сек", rpe: "5–6", easier: "Тяга стоя с опорой, меньший вес", avoid: ["back"] },
      { id: "db-press", name: "Жим гантелей сидя", sets: "2–3", reps: "8–12", rest: "45 сек", rpe: "5–7", easier: "Поочерёдный жим меньшим весом", avoid: [] },
      { id: "rdl", name: "Румынская тяга с гантелями", sets: "2–3", reps: "8–10", rest: "60 сек", rpe: "5–6", easier: "Малый наклон, лёгкий вес", avoid: ["back"] },
      { id: "farmer", name: "Проходка фермера по комнате", sets: "2", reps: "20–30 сек", rest: "60 сек", rpe: "5–6", easier: "Стоять с весом на месте", avoid: [] }
    ],
    gym: [
      { id: "leg-press", name: "Жим ногами в комфортной амплитуде", sets: "2–3", reps: "8–12", rest: "90 сек", rpe: "5–7", easier: "Меньший вес и меньшая глубина", avoid: ["knees", "hips"] },
      { id: "lat-pulldown", name: "Тяга верхнего блока", sets: "2–3", reps: "8–12", rest: "60 сек", rpe: "5–6", easier: "Лёгкий вес, нейтральный хват", avoid: [] },
      { id: "chest-press-m", name: "Жим в тренажёре", sets: "2–3", reps: "8–12", rest: "60 сек", rpe: "5–6", easier: "Меньший вес", avoid: [] },
      { id: "seated-row", name: "Горизонтальная тяга сидя", sets: "2–3", reps: "8–12", rest: "60 сек", rpe: "5–6", easier: "Лёгкий вес", avoid: ["back"] },
      { id: "hip-hinge-cable", name: "Наклон с канатом или румынская тяга", sets: "2–3", reps: "8–10", rest: "75 сек", rpe: "5–6", easier: "Гиперэкстензия с малой амплитудой", avoid: ["back"] }
    ],
    walk: [
      { id: "easy-walk", name: "Спокойная ходьба", sets: "1", reps: "основное время", rest: "по необходимости", rpe: "3–4", easier: "Ходьба с паузами и опорой", avoid: [] },
      { id: "brisk-walk", name: "Ходьба чуть быстрее разговорного темпа", sets: "1", reps: "интервалами по 2–3 мин", rest: "1 мин спокойно", rpe: "4–6", easier: "Только спокойный темп", avoid: ["knees"] }
    ],
    lowImpact: [
      { id: "seated-press", name: "Жим рук сидя без веса или с лёгкими гантелями", sets: "2", reps: "8–10", rest: "60 сек", rpe: "3–5", easier: "Меньше повторений", avoid: [] },
      { id: "sit-stand-slow", name: "Медленные вставания со стула", sets: "2", reps: "6–10", rest: "60 сек", rpe: "4–5", easier: "Только приседания к стулу без полного вставания", avoid: ["knees", "hips"] },
      { id: "heel-raise", name: "Подъёмы на носки у опоры", sets: "2", reps: "8–12", rest: "45 сек", rpe: "3–4", easier: "Меньшая амплитуда", avoid: [] },
      { id: "seated-row-band", name: "Тяга резинки сидя", sets: "2", reps: "8–12", rest: "45 сек", rpe: "3–5", easier: "Слабее натяжение", avoid: [] },
      { id: "step-touch", name: "Шаг в сторону с касанием", sets: "2", reps: "30–45 сек", rest: "45 сек", rpe: "3–4", easier: "Шаги на месте", avoid: ["hips"] }
    ]
  },

  articles: [
    { id: "weight-fluctuation", title: "Почему вес меняется неравномерно", body: "Вес на весах отражает не только жировую ткань. На него влияют вода, соль, объём пищи в кишечнике, гормональный цикл, сон и восстановление после тренировки. Колебание в пределах 0,5–1,5 кг за несколько дней часто бывает обычным. Ориентируйтесь на среднее значение за неделю и самочувствие, а не на одно утреннее взвешивание." },
    { id: "balanced-plate", title: "Как собрать сбалансированную тарелку", body: "Простой ориентир: половину тарелки заполните овощами, четверть — источником белка, четверть — крупой, картофелем или хлебом. Добавьте немного масла, орехов или семян. Это информационный шаблон, а не лечебная схема. Размер порции подбирайте по голоду, рассчитанной калорийности и рекомендациям врача, если они у вас есть." },
    { id: "food-labels", title: "Как читать состав продуктов", body: "Смотрите сначала на список ингредиентов: они указаны по убыванию массы. Затем на порцию и на 100 г. Сахар, соль и насыщенные жиры полезно учитывать в контексте всего дня, а не одного продукта. «0% жира» не делает продукт автоматически более подходящим: иногда там больше сахара. Выбирайте то, что вам подходит по вкусу, бюджету и самочувствию." },
    { id: "eating-out", title: "Как питаться вне дома", body: "Можно заранее выбрать блюдо с овощами и источником белка. Имеет смысл съесть привычную часть порции и остановиться, когда появится насыщение. Не обязательно выбирать «самый диетический» пункт меню. Если день получился плотнее обычного, на следующий вернитесь к обычному ритму без компенсации голодом." },
    { id: "after-overeating", title: "Что делать после переедания", body: "Следующий приём пищи не нужно пропускать в качестве наказания. Полезно вернуться к обычному режиму, добавить овощи и белок, попить воды по жажде и сохранить мягкую активность, например прогулку. Один плотный приём пищи не отменяет прогресс. Жёсткие ограничения после переедания чаще усиливают цикл «срыв — ограничение»." },
    { id: "hunger-types", title: "Как отличить физический голод от эмоционального", body: "Физический голод нарастает постепенно, ощущается в теле и проходит после еды. Эмоциональный часто появляется внезапно, связан с конкретной едой и не всегда связан с пустым желудком. Если сомневаетесь, подождите 10 минут, выпейте воды и спросите себя, что вы чувствуете. Иногда нужна еда, иногда — пауза, разговор или отдых. Ни один из вариантов не является «слабостью»." },
    { id: "after-break", title: "Как вернуться к программе после перерыва", body: "Начните с малого: прежние рабочие веса, длительность и калорийность могут быть избыточными после паузы. Верните 1–2 привычки, затем тренировки меньшей длительности. Не наверстывайте пропущенные дни двойной нагрузкой. Перерыв — часть жизни, а не обнуление результата." },
    { id: "sleep-appetite", title: "Почему сон влияет на аппетит", body: "Недостаток сна может усиливать тягу к быстрым углеводам и снижать ощущение сытости. Это физиология, а не отсутствие силы воли. Если ночь была короткой, разумнее упростить день: более спокойная активность, привычные приёмы пищи и более ранний отход ко сну, когда это возможно." },
    { id: "maintenance", title: "Как сохранить результат", body: "После снижения веса потребность в энергии может быть немного ниже, чем раньше. Сохранение результата обычно связано с регулярными приёмами пищи, посильной активностью и режимом сна, а не с бесконечным дефицитом. Имеет смысл постепенно приближать калорийность к поддерживающему уровню и следить за самочувствием." },
    { id: "spot-reduction", title: "Почему локальное жиросжигание невозможно", body: "Упражнения на живот укрепляют мышцы, но не убирают жир только с этой зоны. Распределение жировой ткани зависит от пола, возраста, генетики и гормонального фона. Общее снижение массы тела при дефиците энергии может уменьшать объёмы, но порядок изменений предсказать точно нельзя." },
    { id: "detox-myths", title: "Почему детокс-чаи и жиросжигатели не заменяют питание и движение", body: "Нет убедительных данных, что чаи, обёртки или «жиросжигатели» обеспечивают устойчивое снижение жировой массы. Часть средств влияет на воду в организме или работу кишечника, что создаёт иллюзию быстрого эффекта. Основа изменений — питание, движение, сон и при необходимости помощь врача. Перед любыми добавками обсудите их со специалистом, особенно при хронических заболеваниях и приёме лекарств." }
  ]
};
